version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
        container_name: www-lamp
            
    db:
        #image: mysql:5.7
        image: mariadb:latest
        # ports: 
        #    - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - db_data:/var/lib/mysql
        networks:
            - default
        container_name: db-lamp
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8888:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        container_name: phpmyadmin-lamp
        
volumes:
    db_data:

# 修正時刻： Sat Jun 20 13:21:12 2020
